### ISSUE TITLE
Предки Адама

### ISSUE THREAD

**Issue by zk-t** [ivan-kleshnin/subjective-js#1]
Решил как-то я заучить js, нашел книжку и начал читать. Чем больше читал, тем больше удивлялся -Как можно писать книгу на русском языке, и делать это так, как не велела Нора Галь.

Стыдно признаться, в голову закралась мысль, -Может автор и вовсе не читал ее [Слово живое и мертвое](https://google.com/search?q=Нора+Галь+-+Слово+живое+и+мертвое). А если не читал, то как же он тогда пишет книгу?

**Comment by ivan-kleshnin** [comment]
Нору читал. Первая половина книги была неплохая. Потом стало скучно – бросил. 
В целом – не впечатлило.

Извините за прямоту, но мнение абстрактного "анонимуса" мне не интересно. Как человек, знающий пять человеческих и около 20 компьютерных языков - я хорошо представляю свои сильные и слабые стороны.
